version: '3'
services:
  backend:
    build: ./backend
    container_name: backend-golang
    command: ["go", "run", "main.go"]
    volumes:
      - ./backend:/go/src/app
    ports:
      - "8080:8080"
